# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Oscar's Site
email: oscarsimpson1999+homepage@gmail.com
description: >-
  A basic website to post my ramblings and anything fun I find
  or want to talk about
baseurl: /homepage
url: https://oscarsimpson.github.io
source_link: https://github.com/oscarsimpson/homepage
github_username:  oscarsimpson

# Build settings
plugins:
  - jekyll-feed
